name: Format

on:
  push:
    branches:
      - main

jobs:
  swift_format:
    name: swift-format
    runs-on: macOS-14
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: |
          brew tap maximkrouk/formulae
          brew install Formulae/swift-format@5.4
      - name: Format
        run: make format
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'ci: swift-format'
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
